development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: simple_wa_dev

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: simple_wa_prod
