default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: 'localhost'


  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simple_wa_connect_development
  username: postgres
  password: postgres
  host: 'localhost'
  encoding: utf8

test:
  <<: *default
  encoding: utf8
  database: simple_wa_connect_test


production:
  primary: &primary_production
    <<: *default
    database: simple_wa_connect_production
    username: simple_wa_connect
    password: <%= ENV["SIMPLE_WA_CONNECT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: simple_wa_connect_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: simple_wa_connect_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: simple_wa_connect_production_cable
    migrations_paths: db/cable_migrate
